project:
  output-dir: _site

format:
  revealjs: 
    slide-number: true
    navigation-mode: vertical
    controls-layout: bottom-right
    controls-tutorial: true
    preview-links: auto
    css: slides.css
