project:
  output-dir: _site

format:
  revealjs: 
    slide-number: true
    navigation-mode: vertical
    controls-layout: bottom-right
    controls-tutorial: true
    preview-links: auto
    css:
      - https://cdnjs.cloudflare.com/ajax/libs/reveal.js/3.6.0/css/theme/white.min.css 
      - slides.css
  pptx:
    css: styles.css